import type { Settings,Telemetry,Transport,MachineState } from '../types';
import {timestamp,normalizeEvent} from './eventService';
export function validDatabaseUrl(raw:string){try{const u=new URL(raw);return u.protocol==='https:'&&/^[a-z0-9-]+(?:\.[a-z0-9-]+)?\.(firebaseio\.com|firebasedatabase\.app)$/.test(u.hostname)&&!u.username&&!u.password&&!u.search&&!u.hash&&['','/'].includes(u.pathname)}catch{return false}}
export function normalizeTelemetry(raw:any,machineId:string):Telemetry|null{if(!raw||typeof raw!=='object')return null;const ts=timestamp(raw.timestamp);const transport:Transport=raw.transport||'WIFI';const status:MachineState=String(raw.machineStatus||raw.status||'').replace('_','-') as MachineState;if(!ts||ts>Date.now()+5000||!['WIFI','LORA_GATEWAY'].includes(transport)||!['RUNNING','IDLE','MICRO-STOPPAGE','STOPPED','OFFLINE'].includes(status)||typeof raw.current!=='number'||!Number.isFinite(raw.current)||raw.current<0||typeof raw.vibration!=='number'||!Number.isFinite(raw.vibration)||raw.vibration<0||(raw.machineId&&raw.machineId!==machineId))return null;return {machineId,timestamp:ts,current:raw.current,vibration:raw.vibration,machineStatus:status,microStoppage:status==='MICRO-STOPPAGE',stoppageDuration:Math.max(0,Number(raw.stoppageDuration)||0),transport,ip:typeof raw.ip==='string'?raw.ip:undefined};}
export class FirebaseAdapter {
 private controller=new AbortController();
 constructor(private settings:Settings,private token:string){}
 stop(){this.controller.abort()}
 private async read(path:string,limit?:number){if(!validDatabaseUrl(this.settings.databaseUrl))throw new Error('Enter a valid Firebase Realtime Database URL in Settings.');const u=new URL(this.settings.databaseUrl.replace(/\/$/,'')+'/'+path+'.json');if(this.token)u.searchParams.set('auth',this.token);if(limit){u.searchParams.set('orderBy','"$key"');u.searchParams.set('limitToLast',String(limit));}const response=await fetch(u,{signal:AbortSignal.any([this.controller.signal,AbortSignal.timeout(10000)])});if(!response.ok)throw new Error(response.status===401||response.status===403?'Firebase access denied. Check your read permissions and session token.':`Firebase connection failed (${response.status}).`);return response.json()}
 async live(){const raw=await this.read(`machines/${encodeURIComponent(this.settings.machineId)}/live`);if(raw==null)return null;const normalized=normalizeTelemetry(raw,this.settings.machineId);if(!normalized)throw new Error('Telemetry does not match the expected machine, units, timestamp or state.');return normalized;}
 async history(){const raw=await this.read(`machines/${encodeURIComponent(this.settings.machineId)}/history`,25000);return Object.values(raw||{}).map(x=>normalizeTelemetry(x,this.settings.machineId)).filter((x):x is Telemetry=>!!x).sort((a,b)=>a.timestamp-b.timestamp);}
 async events(){const raw=await this.read(`machines/${encodeURIComponent(this.settings.machineId)}/events`,5000);return Object.entries(raw||{}).map(([id,e])=>normalizeEvent(e,id,this.settings.machineId)).filter(x=>!!x).sort((a,b)=>b.startTime-a.startTime);}
 async devices(){return (await this.read('system/devices'))||{}}
}
