import { useEffect,useState,useRef } from 'react';
import { defaults,initialSnapshot,type Settings,type Snapshot,type MachineState,type Telemetry } from '../types';
import { FirebaseAdapter } from './firebase';
import { seedDemo,sample,makeEvent } from '../data/mockTelemetry';
import { toast } from 'sonner';
export function useTelemetry(){
 const [settings,setSettings]=useState<Settings>(defaults);const [data,setData]=useState<Snapshot>(initialSnapshot);const [token,setToken]=useState('');const settingsRef=useRef(settings);settingsRef.current=settings;const sourceRef=useRef<'HARDWARE'|'SIMULATION'>('HARDWARE');const hardwareRef=useRef<Telemetry|null>(null);const scenario=useRef<MachineState>('RUNNING');const microStart=useRef<number|null>(null);const eventCounter=useRef(1000);const pendingAfter=useRef<string|null>(null);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('cnc-preferences-v1')||'null');if(saved)setSettings({...defaults,...saved});}catch{}setData(s=>({...s,ready:true}));},[]);
 const saveSettings=(next:Settings,authToken=token)=>{settingsRef.current=next;setSettings(next);setToken(authToken);try{localStorage.setItem('cnc-preferences-v1',JSON.stringify(next))}catch{toast.warning('Settings applied for this session only. Browser storage is unavailable.')}return next;};
 useEffect(()=>{if(!data.ready)return;hardwareRef.current=null;if(!settings.databaseUrl){setData(s=>({...s,databaseState:'unconfigured',error:'',...(s.source==='HARDWARE'?{live:null,history:[],events:[],devices:{},lastSync:null}: {})}));return;}
 const adapter=new FirebaseAdapter(settings,token);let cancelled=false;let timer:ReturnType<typeof setTimeout>;let polls=0;let knownEvents:Set<string>|null=null;setData(s=>({...s,databaseState:'connecting',error:'',...(s.source==='HARDWARE'?{live:null,history:[],events:[],lastSync:null}: {})}));
 async function poll(){try{const live=await adapter.live();if(cancelled)return;hardwareRef.current=live;const fresh=!!live&&Date.now()-live.timestamp<=settings.staleAfter*1000&&live.machineStatus!=='OFFLINE';const takesOver=fresh&&sourceRef.current==='SIMULATION';if(takesOver){sourceRef.current='HARDWARE';scenario.current='RUNNING';microStart.current=null;toast.info('Live hardware connected. Simulation has been stopped.');}
 setData(s=>{const hardware=sourceRef.current==='HARDWARE';const base=takesOver?{history:[],events:[],devices:{}}:{};let history=takesOver?[]:s.history;if(hardware&&live){history=[...history.filter(x=>x.timestamp!==live.timestamp),live].sort((a,b)=>a.timestamp-b.timestamp).slice(-25000);}return {...s,...base,source:sourceRef.current,databaseState:'connected',error:'',lastSync:Date.now(),...(hardware?{live,history}: {})};});
 if(polls++%Math.max(1,Math.round(15/settings.refreshInterval))===0||takesOver){const results=await Promise.allSettled([adapter.history(),adapter.events(),adapter.devices()]);if(cancelled)return;const eventResult=results[1];if(eventResult.status==='fulfilled'&&sourceRef.current==='HARDWARE'){if(knownEvents){for(const e of eventResult.value.filter(e=>!knownEvents!.has(e.id)&&Date.now()-e.endTime<60000)){toast.warning('MICRO-STOPPAGE DETECTED',{description:`${e.machineId} · ${Math.round(e.duration)} seconds · ${new Date(e.endTime).toLocaleTimeString()}`,action:{label:'View event',onClick:()=>window.dispatchEvent(new CustomEvent('cnc-view-event',{detail:e.id}))}});}}knownEvents=new Set(eventResult.value.map(e=>e.id));}setData(s=>{if(s.source!=='HARDWARE')return s;const [h,e,d]=results;const merged=h.status==='fulfilled'?[...new Map([...h.value,...s.history].map(x=>[x.timestamp,x])).values()].sort((a,b)=>a.timestamp-b.timestamp).slice(-25000):s.history;return {...s,history:merged,events:e.status==='fulfilled'?e.value:s.events,devices:d.status==='fulfilled'?d.value:s.devices,historyError:h.status==='rejected'||e.status==='rejected'?'Some history or events could not be loaded. Reports may be incomplete.':''};});}
 }catch(err){if(cancelled)return;hardwareRef.current=null;setData(s=>({...s,databaseState:'error',error:err instanceof Error?err.message:'Connection failed.'}));}if(!cancelled)timer=setTimeout(poll,settings.refreshInterval*1000);}
 poll();return()=>{cancelled=true;clearTimeout(timer);adapter.stop()};
 },[settings.machineId,settings.databaseUrl,settings.refreshInterval,settings.staleAfter,token,data.ready]);
 useEffect(()=>{if(data.source!=='SIMULATION')return;const handle=setInterval(()=>{const now=Date.now(),cfg=settingsRef.current;let state=scenario.current;const start=microStart.current;let completed:any=null;if(start&&now-start>=Math.min(cfg.maxDuration,Math.max(cfg.minDuration,7))*1000){scenario.current='RUNNING';state='RUNNING';microStart.current=null;completed={id:`SIM-${++eventCounter.current}`,start,end:start+Math.min(cfg.maxDuration,Math.max(cfg.minDuration,7))*1000};pendingAfter.current=completed.id;}
 setData(s=>{if(s.source!=='SIMULATION')return s;const live=sample(now,state,cfg,start?(now-start)/1000:0);const history=[...s.history,...(completed&&completed.end<now?[sample(completed.end,'RUNNING',cfg)]:[]),live].slice(-25000);let events=s.events;if(completed){const e=makeEvent(completed.id,completed.start,completed.end,cfg,history);events=[e,...events];}else if(pendingAfter.current){events=events.map(e=>e.id===pendingAfter.current?{...e,samples:history.filter(x=>x.timestamp>=e.startTime-20000&&x.timestamp<=e.endTime+20000)}:e);const e=events.find(e=>e.id===pendingAfter.current);if(e&&now>e.endTime+20000)pendingAfter.current=null;}return {...s,live,history,events,scenario:state};});if(completed)toast.warning('MICRO-STOPPAGE DETECTED',{description:`${cfg.machineId} · ${Math.round((completed.end-completed.start)/1000)} seconds · Simulated event`,action:{label:'View event',onClick:()=>window.dispatchEvent(new CustomEvent('cnc-view-event',{detail:completed.id}))}});
 },1000);return()=>clearInterval(handle);},[data.source]);
 function startSimulation(){const hardware=hardwareRef.current;if(hardware&&Date.now()-hardware.timestamp<settingsRef.current.staleAfter*1000&&hardware.machineStatus!=='OFFLINE'){toast.error('Live hardware is connected and has priority.');return false;}sourceRef.current='SIMULATION';scenario.current='RUNNING';microStart.current=null;pendingAfter.current=null;const demo=seedDemo(settingsRef.current);setData(s=>({...s,...demo,source:'SIMULATION',scenario:'RUNNING',historyError:''}));toast.info('Simulation enabled. All displayed telemetry is generated demo data.');return true;}
 function stopSimulation(){sourceRef.current='HARDWARE';scenario.current='RUNNING';microStart.current=null;pendingAfter.current=null;setData(s=>({...s,source:'HARDWARE',live:hardwareRef.current,history:[],events:[],scenario:'RUNNING',historyError:''}));toast.info('Simulation stopped. Waiting for real CNC telemetry.');}
 function runScenario(state:MachineState){if(sourceRef.current!=='SIMULATION')return false;if(microStart.current!==null){toast.info('Let the current micro-stoppage finish before changing scenarios.');return false;}scenario.current=state;if(state==='MICRO-STOPPAGE')microStart.current=Date.now();const transition=sample(Date.now(),state,settingsRef.current);setData(s=>({...s,scenario:state,live:transition,history:[...s.history,transition]}));return true;}
 return {data,settings,token,saveSettings,startSimulation,stopSimulation,runScenario};
}
