'use client';
import {useEffect,useState} from 'react';
import {FileChartColumn,Download,Printer,ArrowRight} from 'lucide-react';
import {toast} from 'sonner';
import {Panel,Choice,NoData} from '../components/Common';
import {EventTable} from '../components/Events';
import {useApp} from '../context';
import {metrics,monetaryLoss} from '../utils/calculations';
import {num,duration,dayKey,fullDate,money} from '../utils/formatters';
import {downloadCsv,eventRows} from '../services/eventService';
export function Reports(){const {data,settings,now}=useApp();const [type,setType]=useState('daily');const [date,setDate]=useState(dayKey(now));const [report,setReport]=useState<{m:ReturnType<typeof metrics>;source:string;name:string;date:string;machine:string;cycle:number;rate:number|null;created:number}|null>(null);useEffect(()=>setReport(null),[data.source,settings.machineId]);function generate(){if(!date){toast.error('Choose a report date.');return;}const start=new Date(date+'T00:00:00');if(!Number.isFinite(start.getTime())){toast.error('Choose a valid date.');return;}const end=new Date(date+'T23:59:59.999');if(type==='weekly')start.setDate(start.getDate()-6);const m=metrics(data.history,data.events,start.getTime(),Math.min(now,end.getTime()),Math.max(settings.staleAfter,6));if(!m.samples.length&&!m.events.length){toast.info('No records are available for this period.');setReport(null);return;}setReport({m,source:data.source==='SIMULATION'?'SIMULATION':'LIVE HARDWARE',name:type,date:type==='weekly'?`${dayKey(start.getTime())} to ${date}`:date,machine:settings.machineId,cycle:settings.cycleTime,rate:settings.downtimeCostPerMinute,created:now});toast.success('Report generated from the currently loaded records.');}const names:Record<string,string>={daily:'Daily Report',weekly:'Weekly Report',micro:'Micro-Stoppage Report',performance:'Machine Performance Report'};const r=report;const rows=r?[['Operating time',duration(r.m.running)],['Total downtime',duration(r.m.downtime)],['Micro-stoppages',String(r.m.count)],['Micro-stop duration',duration(r.m.micro)],['Machine utilization',num(r.m.utilization,1)+'%'],['Downtime',num(r.m.downtimePct,1)+'%'],['Average current',num(r.m.avgCurrent)+' A'],['Average vibration',num(r.m.avgVibration)+' g'],['Longest stoppage',duration(r.m.longest)],['Estimated production loss',num(r.m.loss,1)+'%'],['Estimated micro-stop loss (INR)',money(monetaryLoss(r.m.micro,r.rate))],['Assumed downtime cost',r.rate==null?'Not configured':`${money(r.rate)}/min`],['Estimated units lost',num(r.m.micro/r.cycle,1)],['Observed available time',duration(r.m.available)]]:[];
function exportReport(){if(!r)return;if(r.name==='micro'){downloadCsv(`CNC-${r.name}-${date}.csv`,eventRows(r.m.events,r.rate));return;}downloadCsv(`CNC-${r.name}-${date}.csv`,[{report_type:names[r.name],machine:r.machine,source:r.source,period:r.date,generated_at:new Date(r.created).toISOString(),operating_seconds:r.m.running,idle_seconds:r.m.durations.IDLE,downtime_seconds:r.m.downtime,observed_available_seconds:r.m.available,micro_stoppages:r.m.count,micro_stop_seconds:r.m.micro,utilization_percent:r.m.utilization,downtime_percent:r.m.downtimePct,average_current_A:r.m.avgCurrent,average_vibration_g:r.m.avgVibration,longest_stoppage_seconds:r.m.longest,estimated_production_loss_percent:r.m.loss,estimated_micro_stop_loss_INR:monetaryLoss(r.m.micro,r.rate),assumed_cost_INR_per_minute:r.rate,cost_basis:'recorded_micro_stoppage_duration',estimated_units_lost:r.m.micro/r.cycle,cycle_time_seconds:r.cycle}]);}
return <><Panel title="Generate a production report" icon={FileChartColumn} className="no-print"><div className="filters"><label style={{minWidth:220}}>Report type<Choice label="Report type" value={type} onChange={setType} options={Object.entries(names).map(([value,label])=>({value,label}))}/></label><label>Report date{type==='weekly'?' · week ending':''}<input type="date" value={date} max={dayKey(now)} onChange={e=>setDate(e.target.value)}/></label><button className="btn btn-primary" onClick={generate}>Generate Report <ArrowRight/></button></div></Panel><div style={{height:20}}/>{r?<Panel title={`${names[r.name]} · ${r.machine}`} className="print-report" subtitle={`${r.date} · ${r.source}`} action={<div className="head-actions no-print"><button className="btn" onClick={()=>window.print()}><Printer/>Print</button><button className="btn" disabled={r.name==='micro'&&!r.m.events.length} onClick={exportReport}><Download/>Export CSV</button></div>}><div className="panel-body"><div className={`note ${r.source==='SIMULATION'?'warn':''}`}>{r.source==='SIMULATION'?'SIMULATION REPORT — Generated demo data. Does not represent a physical CNC machine.':'HARDWARE REPORT — Based on records loaded from the configured machine.'}</div><div className="report-summary">{rows.map(([k,v])=><div key={k}><label>{k}</label><strong>{v}</strong></div>)}</div><p className="muted" style={{fontSize:12,marginTop:20}}>Generated {new Date(r.created).toLocaleString('en-GB')}. Utilization uses observed time, excluding telemetry gaps. Production estimates assume {r.cycle} seconds per unit. Idle time is excluded from downtime but included in available time. Money loss uses recorded micro-stop seconds ÷ 60 × the assumed rate captured when this report was generated. {r.rate==null?'No cost rate was configured, so monetary values are unavailable.':`Rate: ${money(r.rate)} per minute. This is an estimate of recorded loss, not a future prediction.`} It excludes idle and sustained stopped time.</p></div>{(r.name==='micro'||r.name==='daily')&&<EventTable events={r.m.events} compact/>}</Panel>:<section className="panel"><NoData title="Your report starts here" description="Choose a report type and date, then generate a summary from recorded telemetry."/></section>}</>}
