'use client';
import {useEffect,useRef} from 'react';
import {Chart,registerables} from 'chart.js';
import {Activity,Zap,Radio} from 'lucide-react';
import {Panel} from './Common';
import {num,time} from '../utils/formatters';
import type {Telemetry} from '../types';
Chart.register(...registerables);
export function DataChart({labels,values,color='#efb547',type='line',threshold,unit='',region}:{labels:string[];values:number[];color?:string;type?:'line'|'bar';threshold?:number;unit?:string;region?:[number,number]}){const canvas=useRef<HTMLCanvasElement>(null);const chart=useRef<Chart|null>(null);const optsRef=useRef({region});optsRef.current={region};useEffect(()=>{if(!canvas.current)return;const instance=new Chart(canvas.current,{type,data:{labels:[],datasets:[]},options:{responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{backgroundColor:'#232c38',titleColor:'#e6edf5',bodyColor:'#c1ccd8',padding:11,displayColors:false,callbacks:{label:ctx=>`${num(Number(ctx.parsed.y))} ${unit}`}}},scales:{x:{grid:{display:false},ticks:{color:'#7e8c9e',maxTicksLimit:7,maxRotation:0,font:{size:10}},border:{display:false}},y:{beginAtZero:true,grid:{color:'#29323e80'},ticks:{color:'#7e8c9e',maxTicksLimit:4,font:{size:10}},border:{display:false}}}},plugins:[{id:'eventRegion',beforeDatasetsDraw(c){const r=optsRef.current.region;if(!r)return;const {ctx,chartArea,scales}=c;const from=scales.x.getPixelForValue(r[0]),to=scales.x.getPixelForValue(r[1]);ctx.save();ctx.fillStyle='#efb54720';ctx.fillRect(from,chartArea.top,Math.max(3,to-from),chartArea.bottom-chartArea.top);ctx.restore();}}]});chart.current=instance;return()=>{instance.destroy();chart.current=null}},[type,unit]);useEffect(()=>{if(!chart.current)return;chart.current.data.labels=labels;chart.current.data.datasets=[{data:values,borderColor:color,backgroundColor:type==='bar'?color:color+'0e',fill:type==='line',borderWidth:type==='bar'?0:1.8,pointRadius:0,pointHoverRadius:4,tension:.3,barPercentage:.6,borderRadius:type==='bar'?3:0},...(threshold!=null?[{data:labels.map(()=>threshold),borderColor:'#818b9955',borderDash:[5,5],borderWidth:1,pointRadius:0,fill:false}]:[])];chart.current.update('none');},[labels,values,color,threshold]);return <canvas ref={canvas} role="img" aria-label={`${type==='bar'?'Bar':'Line'} chart with ${values.length} samples, ${unit||'count'}`}/>}
export function SensorChart({history,metric,threshold,large=false,region,title}:{history:Telemetry[];metric:'current'|'vibration';threshold?:number;large?:boolean;region?:[number,number];title?:string}){const values=history.map(h=>h[metric]),labels=history.map(h=>time(h.timestamp,false));const current=metric==='current',unit=current?'A':'g',color=current?'#efb547':'#66b8ca';return <Panel title={title||(current?'Motor current':'Vibration')} icon={current?Zap:Activity} className="chart-panel" action={<div className="chart-stat" style={{color}}>{num(values.at(-1))}<small>{unit}</small></div>}><div className={`chart-body ${large?'large':''}`}><DataChart values={values} labels={labels} color={color} threshold={threshold} unit={unit} region={region}/>{!values.length&&<div className="empty-chart"><Radio size={18}/>Waiting for sensor data</div>}</div><div className="chart-foot"><span>AVG<strong>{num(values.length?values.reduce((a,b)=>a+b,0)/values.length:null)}</strong></span><span>MIN<strong>{num(values.length?Math.min(...values):null)}</strong></span><span>MAX<strong>{num(values.length?Math.max(...values):null)}</strong></span>{threshold!=null&&<span style={{marginLeft:'auto'}}>Threshold {num(threshold)} {unit}</span>}</div></Panel>}
export function AnalyticsChart({title,labels,values,unit='',color,type='bar'}:{title:string;labels:string[];values:number[];unit?:string;color?:string;type?:'line'|'bar'}){return <Panel title={title} subtitle={unit||'Detected events'}><div className="chart-body large" style={{padding:'18px 18px 12px'}}><DataChart labels={labels} values={values} unit={unit} color={color} type={type}/>{!values.length&&<div className="empty-chart">No data in this period</div>}</div></Panel>}
